repos:
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        language_version: python3
        args: ["--filter-files"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
        language_version: python3
      - id: check-added-large-files
        language_version: python3
      - id: check-ast
        language_version: python3
      - id: check-yaml
        language_version: python3
      - id: check-json
        language_version: python3
      - id: detect-private-key
        language_version: python3
      - id: flake8
        language_version: python3
