run: PPO
base:
  gamma: 0.95
  lr: 0.0001
  vf_loss_coeff: 0.01
  clip_rewards: false
  train_batch_size:  20000
  sgd_minibatch_size: 256

  model:
    custom_model: gnn_net
    custom_model_config:
      activation: ELU
      dims:
        - [32, 10]
        - [32, 10]

  env: spg_graph
  env_config:
    pg_name: "wall/dispenser_fireballs"

tune:
  env_config/pg_name:
    type: grid_search
    args:
      - "wall/candy_fireballs_large"
      - "wall/candy_poison_large"
      - "wall/dispenser_fireballs_large"
      - "wall/dispenser_fireballs"
      - "wall/candy_fireballs"
      - "wall/candy_poison"

search_alg: hyperopt
scheduled: AsyncHyperBandScheduler
metric: episode_reward_mean
