run: PPO
base:
  gamma: 0.95
  lr: 0.0001
  vf_loss_coeff: 0.1
  clip_rewards: false
  train_batch_size:  20000
  sgd_minibatch_size: 512

  model:
    custom_model: cnn1d_net
    conv_filters:
      - [64, 5, 2]
      - [64, 3, 2]
      - [128, 3, 2]
      - [128, 3, 1]
      - [128, 3, 1]

  env: spg_stacked
  env_config:
    pg_name: "wall/candy_poison"

tune:
  env_config/pg_name:
    type: grid_search
    args:
      - "wall/candy_poison_large"
      - "wall/candy_fireballs_large"
      - "wall/dispenser_fireballs_large"
      - "wall/candy_poison"
      - "wall/candy_fireballs"
      - "wall/dispenser_fireballs"


search_alg: hyperopt
scheduled: AsyncHyperBandScheduler
metric: episode_reward_mean
