run: PPO
base:
  gamma: 0.95
  lr: 0.001
  vf_loss_coeff: 0.0001
  clip_rewards: false
  train_batch_size:  20000
  sgd_minibatch_size: 500

  model:
    custom_model: attn_net
    custom_model_config:
      num_slots: 20
      hidden_dim: 512

  env: spg_set
  env_config:
    pg_name: "wall/dispenser_fireballs"

tune:
  env_config/pg_name:
    type: grid_search
    args:
      - "wall/candy_fireballs_large"
      - "wall/candy_poison_large"
      - "wall/candy_fireballs"
      - "wall/candy_poison"
      - "wall/dispenser_fireballs"
      - "wall/dispenser_fireballs_large"

search_alg: hyperopt
scheduled: AsyncHyperBandScheduler
metric: episode_reward_mean
