run: PPO
gpu_per_worker: 1
base:
  gamma: 0.99
  lr: 0.0001
  clip_rewards: false
  model:
    custom_model: fc-net
    fcnet_hiddens: [64, 32, 32]

  env: spg-flat
  env_config:
    pg_name: "basic_rl/candy_poison"
    sensors_name: "rgb_depth"

tune:
  vf_loss_coeff:
    type: grid_search
    args:
      - - 0.01
        - 0.1
        - 1.0
        - 10.0
  lr:
    type: grid_search
    args:
      - - 0.00001
        - 0.0001
        - 0.001
        - 0.01
        - 0.1

search_alg: hyperopt
scheduled: AsyncHyperBandScheduler
metric: episode_reward_mean
