run: PPO
base:
  gamma: 0.95
  lr: 0.001
  vf_loss_coeff: 0.01
  clip_rewards: false
  train_batch_size: 20000
  sgd_minibatch_size: 512
  entropy_coeff: 0.01
  kl_coeff: 0.0
  num_sgd_iter: 30

  model:
    custom_model: enros
    custom_model_config:
      encoder:
        entity:
          name: EntityPassThrough
        scene:
          name: GNNEncoder
          config:
            conv:
              activation: ELU
              dims:
                - [8, 8]
                - [8, 1]

  env: spg_set_wrapped
  env_config:
    pg_name: "wall/dispenser_fireballs"
    wrap:
      stack: 2

tune:
  env_config/pg_name:
    type: grid_search
    args:
      - "wall/candy_fireballs_large"
      - "wall/candy_poison_large"
      - "wall/dispenser_fireballs_large"
      - "wall/candy_fireballs"
      - "wall/candy_poison"
      - "wall/dispenser_fireballs"

search_alg: hyperopt
scheduled: AsyncHyperBandScheduler
metric: episode_reward_mean

args:
  num_workers: 10
  envs_per_worker: 1
  checkpoint_freq: 50
  cpus_per_worker: 0.001
  num_gpus: 0.32
  # num_gpus: 0.49
  stop_at: 8000000
  worker_gpu: false
  no_sched: true
  tune: true
  num_samples: 2
  # concurrency: 8
  amp: false
