run: PPO
base:
  lambda: 0.95
  kl_coeff: 0.5
  clip_rewards: True
  clip_param: 0.1
  vf_clip_param: 10.0
  entropy_coeff: 0.01
  train_batch_size: 5000
  rollout_fragment_length: 20
  sgd_minibatch_size: 500
  num_sgd_iter: 10
  num_gpus: 1
  model:
    dim: 42
    vf_share_layers: true

  env: "PongNoFrameskip-v4"

tune:
  env:
    type: grid_search
    args:
      - "SkiingNoFrameskip-v4"
      - "BreakoutNoFrameskip-v4"
      - "SpaceInvadersNoFrameskip-v4"
      - "PongNoFrameskip-v4"


search_alg: hyperopt
scheduled: AsyncHyperBandScheduler
metric: episode_reward_mean
