run: PPO
base:
  batch_mode: truncate_episodes

  clip_rewards: false
  train_batch_size:  5000
  sgd_minibatch_size: 500

  gamma: 0.99
  lr: 0.001
  clip_param: 4.2
  entropy_coeff: 0.00002
  vf_loss_coeff: 0.0023
  grad_clip: 0.012
  kl_coeff: 0.20
  num_sgd_iter: 10

  model:
    custom_model: enros
    custom_model_config:
      encoder:
        entity:
          name: EntityPassThrough
        scene:
          name: GNNEncoder
          config:
            conv:
              activation: ELU
              dims:
                - [16, 8]
                - [16, 8]

  env: atari_graph
  env_config:
   pg_name: "PongNoFrameskip-v4"
   wrap:
      skip: 4
      stack: 4
      resize: 100

tune:
  env_config/pg_name:
    type: grid_search
    args:
      - "PongNoFrameskip-v4"
      - "BreakoutNoFrameskip-v4"
      - "SpaceInvadersNoFrameskip-v4"
      - "SkiingNoFrameskip-v4"

search_alg: hebo
scheduled: AsyncHyperBandScheduler
metric: episode_reward_mean
